# about.py
import dash_bootstrap_components as dbc
from dash import html

layout = dbc.Container(
    [
        # Title
        html.H2("About PolyGenie", className="mb-4"),
        html.Hr(),

        # Section 1: What is PolyGenie?
        html.H4("What is PolyGenie?"),
        html.P(
            "PolyGenie is a cohort-agnostic framework for phenome-wide association studies (PheWAS) "
            "based on polygenic risk scores (PRS). It provides a reproducible analysis pipeline and "
            "an interactive web interface for exploring associations between precomputed PRS and "
            "a wide range of phenotypes across population cohorts."
        ),

        html.P(
            "PolyGenie does not perform PRS computation. Instead, it is designed to ingest PRS "
            "generated by external tools and integrate them with cohort-level phenotype data "
            "to enable systematic PRS–phenotype association analyses."
        ),

        html.P(
            "The framework is cohort-agnostic and can be applied to any dataset with compatible "
            "PRS and phenotype information. Here, we showcase its application using the GCAT "
            "(Genomes for Life) cohort as a representative use case."
        ),

        html.Hr(),

        # Section 2: Methodology + Diagram
        html.H4("How It Works"),
        html.P(
            "PolyGenie operates downstream of PRS construction. Precomputed PRS, together with "
            "cohort-specific phenotype data, are provided as inputs to a scalable Nextflow-based "
            "pipeline that performs phenome-wide association scans and stratified analyses."
        ),

        html.P(
            "In the GCAT use case presented here, PRS were computed externally using the MegaPRS "
            "method through the GenoPred pipeline prior to running PolyGenie. These scores were "
            "then analyzed by PolyGenie to assess associations with diseases, biomarkers, lifestyle "
            "traits, and environmental exposures."
        ),

        html.P(
            "PolyGenie produces standardized association statistics and summary measures that are "
            "stored in a structured database and exposed through an interactive web interface. "
            "This interface, which is a core component of the PolyGenie framework, enables intuitive "
            "exploration of PRS distributions, PRS–phenotype associations, and phenotype prevalence "
            "across PRS percentiles."
        ),

        html.Img(
            src="/assets/polygenie-schema.png",
            style={
                "maxWidth": "100%",
                "borderRadius": "8px",
                "boxShadow": "0 0 10px rgba(0,0,0,0.1)"
            }
        ),
        html.Small(
            "Figure: Overview of the PolyGenie framework. PolyGenie operates downstream of PRS "
            "computation, ingesting precomputed PRS to perform phenome-wide association analyses "
            "and interactive result exploration.",
            className="text-muted"
        ),

        html.Hr(),
       
        # Section: Getting Started Tutorial
        html.H4("Getting Started"),
        html.P(
            "The following walkthrough shows how to reproduce the Frailty PRS analysis "
            "presented in our paper, using overweight/obesity and major depressive disorder "
            "as example outcomes."
        ),
        html.Ol([
            html.Li([
                html.Strong("Select a PRS of interest. "),
                "From the navigation menu, go to the PRS Visualisation page. "
                "In the 'Select PRS' dropdown, search for and select 'Fried Frailty'. "
                "The PheWAS scatter plot will load automatically, showing associations across all phenotypic domains."
            ], style={"marginBottom": "10px"}),
            html.Li([
                html.Strong("Choose a comparison group. "),
                "Use the 'Reference Group' selector to choose how the top PRS group is compared against the rest of the cohort. "
                "For the frailty example, select 'Bottom' and '10 (deciles)' to match the analysis shown in the paper."
            ], style={"marginBottom": "10px"}),
            html.Li([
                html.Strong("Explore the PheWAS scatter plot. "),
                "Each point represents a phenotype, grouped by domain along the x-axis. "
                "The y-axis shows the signed log₁₀(p-value): points above zero indicate positive associations, "
                "points below indicate negative ones. Hover over any point to see the effect size, p-value, and number of cases."
            ], style={"marginBottom": "10px"}),
            html.Li([
                html.Strong("Choose the significance threshold. "),
                "Use the new 'Significance threshold' selector to choose how association thresholds are drawn. "
                "The default setting is 'Bonferroni (domain-wise)', which divides alpha by the number of unique domains. "
                "You can also choose 'Bonferroni (global)' for correction across all tested phenotypes, or "
                "'FDR (global)' to control the false discovery rate across the entire plot."
            ], style={"marginBottom": "10px"}),
            html.Li([
                html.Strong("Click a point to open the prevalence-by-percentile plot. "),
                "Click on any point in the scatter plot — for example, E66 (Overweight and obesity) or "
                "F32 (Major depressive disorder) — to load the prevalence plot below. "
                "Remember you can zoom in the plot by 'drawing' a square with the mouse. "
                "This shows how the prevalence of that condition changes across the full PRS distribution, "
                "with separate lines for males and females. "
                "For obesity, prevalence rises approximately linearly with similar trends in both sexes. "
                "For major depression, females show consistently higher rates across all percentiles, "
                "roughly twice those of males."
            ], style={"marginBottom": "10px"}),
            html.Li([
                html.Strong("Export the results. "),
                "The full association table below the plots can be sorted, filtered, and downloaded as an Excel file "
                "using the 'Download Table' button."
            ], style={"marginBottom": "10px"}),
        ], style={"paddingLeft": "20px", "lineHeight": "1.8"}),
        html.Hr(),
        # Section 3: Contact & Citation
        html.H4("Contact and Citation"),
        html.P(
            "PolyGenie is developed and maintained by researchers at GCAT | Genomes for Life, "
            "Institut Germans Trias i Pujol."
        ),
        html.P(
            [
                "For questions or feature suggestions, please contact us at ",
                html.A("contact email", href="mailto:gcat@igtp.cat"),
                "."
            ]
        ),
        html.P(
            [
                "GitHub: ",
                html.A("PolyGenie repository", href="https://github.com/gcatbiobank/polygenie-gcat", target="_blank")
            ]
        ),
        html.P(
            "If you use PolyGenie in your research, please cite our forthcoming application note."
        ),
    ],
    className="mt-4 mb-5"
)



